# Generated by Django 4.0.2 on 2022-02-23 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_from', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=40)),
                ('message', models.CharField(max_length=300)),
            ],
        ),
    ]
